version: '2'
services:
    mongodb:
        image: mvertes/alpine-mongo
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user 
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: sensors
        ports:
            - 27017:27017
        volumes:
            - ./mongo_data:/data/db